name: Testing E2E iOS

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  ios:
    name: iOS
    runs-on: macos-latest
    # TODO matrix across APIs, at least 10 and 13 (lowest to highest)
    timeout-minutes: 60
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1

      - uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        name: Yarn Cache
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-yarn-v1

      - uses: actions/cache@v2
        name: Cache Pods
        with:
          path: tests_react_native/ios/Pods
          key: ${{ runner.os }}-pods-v2-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods-v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3

      - name: Update Ruby build tools
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 2
          retry_wait_seconds: 60
          max_attempts: 3
          command: gem update cocoapods xcodeproj

      - name: Yarn Install
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: yarn --no-audit --prefer-offline && npm i -g cavy-cli

      - name: Install applesimutils
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew tap wix/brew && HOMEBREW_NO_AUTO_UPDATE=1 brew install applesimutils && applesimutils --list

      - name: Pre-fetch Javascript bundle
        run: |
          nohup yarn tests_rn:packager &
          printf 'Waiting for packager to come online'
          until curl --output /dev/null --silent --head --fail http://localhost:8081/status; do
            printf '.'
            sleep 2
          done
          echo "Packager is online! Preparing bundle..."
          curl --output /dev/null --silent --head --fail "http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&inlineSourceMap=true"
          echo "...javascript bundle ready"

      - uses: hendrikmuhs/ccache-action@v1
        name: Xcode Compile Cache
        with:
          key: ${{ runner.os }}-v2 # makes a unique key w/related restore key internally
          max-size: 400M

      - name: Build App, Boot Simulator, Run App
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          export CCACHE_SLOPPINESS=clang_index_store,file_stat_matches,include_file_ctime,include_file_mtime,ivfsoverlay,pch_defines,modules,system_headers,time_macros
          export CCACHE_FILECLONE=true
          export CCACHE_DEPEND=true
          export CCACHE_INODECACHE=true
          ccache -s
          export SKIP_BUNDLING=1
          export RCT_NO_LAUNCH_PACKAGER=1
          yarn run:ios
          ccache -s
        shell: bash

      - name: Create Simulator Log
        # With a little delay, missing the first part of boot is fine, it will still capture app issues
        continue-on-error: true
        run: nohup sh -c "sleep 10 && xcrun simctl spawn booted log stream --level debug --style compact > simulator.log 2>&1 &"

      - name: Grant Notification Permission
        run: applesimutils --booted --setPermissions notifications=YES --bundle com.notifee.testing

      - name: Restart App
        # The permission grant restarts Springboard, so we launch cleanly again here
        run: yarn run:ios

      - name: E2E Test
        timeout-minutes: 30
        continue-on-error: true
        run: yarn tests_rn:ios:test-ci

      - name: Compress Simulator Log
        if: always()
        run: gzip -9 simulator.log

      - name: Upload Simulator Log
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: simulator_logs
          path: simulator.log.gz

      - name: Submit Coverage
        # This can fail on timeouts etc, wrap with retry
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: curl https://codecov.io/bash -o codecov.sh && bash ./codecov.sh
